require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/decorators/*'

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 12

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Max: 8

AllCops:
  NewCops: enable
  Exclude:
    - 'db/*'
    - 'spec/spec_helper.rb'
