Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 12

AllCops:
  NewCops: enable
  Exclude:
    - 'db/*'
    - 'spec/spec_helper.rb'
